using UnityEngine;

/// <summary>
/// Simple utility to build a square room from prefabs: floor, walls and doors.
/// Put this component on an empty GameObject and call Build(size) to create children.
/// It scales prefabs to match the given size using their Renderer bounds as base size.
/// </summary>
[ExecuteAlways]
public class RoomBuilder : MonoBehaviour
{
    [Header("Prefabs (assign in inspector)")]
    public GameObject floorPrefab;
    public GameObject wallPrefab;
    public GameObject doorPrefab;

    [Header("Layout options")]
    // wall thickness in world units (used if wall prefab has unit width/height)
    public float wallThickness = 0.5f;
    // how far doors sit outside the room collider when placed
    public float doorOutsideOffset = 0.1f;
    // default side length to use when callers do not supply an explicit size
    public float defaultSize = 8f;
    // whether to clear existing children when Build is called.
    // If true: remove existing children (except those containing EnemySpawner to avoid breaking references).
    // If false: preserve existing children and only replace children previously generated by this builder.
    // Default: false (preserve) to avoid accidental data loss.
    public bool clearExistingChildren = false;

    // Public API: build a square room with side length 'size' (world units)
    public void Build(float size)
    {
        // Always run ClearChildren() to remove any previous builder-generated children.
        // ClearChildren() will inspect `clearExistingChildren` to decide whether to
        // perform a full clear or a conservative (marked-only) clear.
        ClearChildren();

        // create floor
        GameObject floor = null;
        if (floorPrefab != null)
        {
            floor = Instantiate(floorPrefab, transform);
            // mark generated objects so we can safely clear them later without touching designer-placed content
            floor.AddComponent<RoomBuilderMarker>();
        }
        else
        {
            floor = new GameObject("Floor");
            floor.transform.SetParent(transform, false);
            var sr = floor.AddComponent<SpriteRenderer>();
            sr.color = Color.gray;
            floor.AddComponent<RoomBuilderMarker>();
        }
        ScaleToSize(floor, new Vector2(size + wallThickness, size + wallThickness));
        floor.transform.localPosition = Vector3.zero;

        // create 4 walls as segments so each side is: left-wall / door-gap / right-wall
        // measure door size in world units (fallback to 1f if missing)
        float doorWidth = 1f;
        if (doorPrefab != null)
        {
            var dr = doorPrefab.GetComponentInChildren<Renderer>();
            if (dr != null)
            {
                // for horizontal doors (N/S) we use x size; for vertical doors (E/W) we'll use y size later
                doorWidth = dr.bounds.size.y;
                if (doorWidth <= 0f) doorWidth = 1f;
            }
        }

        // Horizontal walls (north/south): split by doorWidth
        float halfGapH = Mathf.Max(0f, (size - doorWidth) / 2f);
        // ensure small overlap at corners by adding wallThickness
        float leftLenH = halfGapH + wallThickness;
        float rightLenH = leftLenH;

        // North: left segment
        CreateWall(new Vector2(- (doorWidth / 2f + leftLenH / 2f), (size / 2f) + (wallThickness / 2f)), new Vector2(leftLenH, wallThickness), 0f, "Wall_North_Left");
        // North: right segment
        CreateWall(new Vector2((doorWidth / 2f + rightLenH / 2f), (size / 2f) + (wallThickness / 2f)), new Vector2(rightLenH, wallThickness), 0f, "Wall_North_Right");

        // South: left
        CreateWall(new Vector2(- (doorWidth / 2f + leftLenH / 2f), -(size / 2f) - (wallThickness / 2f)), new Vector2(leftLenH, wallThickness), 0f, "Wall_South_Left");
        // South: right
        CreateWall(new Vector2((doorWidth / 2f + rightLenH / 2f), -(size / 2f) - (wallThickness / 2f)), new Vector2(rightLenH, wallThickness), 0f, "Wall_South_Right");

        // Vertical walls (east/west): need door height; measure doorPrefab vertical extent if available
        float doorHeight = 1f;
        if (doorPrefab != null)
        {
            var dr = doorPrefab.GetComponentInChildren<Renderer>();
            if (dr != null)
            {
                doorHeight = dr.bounds.size.y;
                if (doorHeight <= 0f) doorHeight = 1f;
            }
        }

        float halfGapV = Mathf.Max(0f, (size - doorHeight) / 2f);
        float leftLenV = halfGapV + wallThickness;
        float rightLenV = leftLenV;

        // East: bottom segment
        CreateWall(new Vector2((size / 2f) + (wallThickness / 2f), - (doorHeight / 2f + leftLenV / 2f)), new Vector2(wallThickness, leftLenV), 0f, "Wall_East_Bottom");
        // East: top segment
        CreateWall(new Vector2((size / 2f) + (wallThickness / 2f), (doorHeight / 2f + rightLenV / 2f)), new Vector2(wallThickness, rightLenV), 0f, "Wall_East_Top");

        // West: bottom
        CreateWall(new Vector2(-(size / 2f) - (wallThickness / 2f), - (doorHeight / 2f + leftLenV / 2f)), new Vector2(wallThickness, leftLenV), 0f, "Wall_West_Bottom");
        // West: top
        CreateWall(new Vector2(-(size / 2f) - (wallThickness / 2f), (doorHeight / 2f + rightLenV / 2f)), new Vector2(wallThickness, rightLenV), 0f, "Wall_West_Top");

        // create doors at midpoint of each wall (place in front)
        if (doorPrefab != null)
        {
            // North
            CreateDoor(new Vector3(0f, size / 2f + doorOutsideOffset, 0f), 90f, "Door_North");
            // South
            CreateDoor(new Vector3(0f, -size / 2f - doorOutsideOffset, 0f), -90f, "Door_South");
            // East
            CreateDoor(new Vector3(size / 2f + doorOutsideOffset, 0f, 0f), 0f, "Door_East");
            // West
            CreateDoor(new Vector3(-size / 2f - doorOutsideOffset, 0f, 0f), 0f, "Door_West");
        }

        // NOTE: RoomBuilder only generates floor/walls/doors. It does NOT modify RoomManager
        // or create room triggers. RoomManager can optionally call RoomBuilder to auto-generate
        // the visual geometry, or the designer can place these objects manually.
        // Create or update a BoxCollider2D on the same GameObject to act as the room trigger.
        // This makes the builder fully responsible for room geometry + logical bounds.
        var existing = GetComponent<BoxCollider2D>();
        if (existing == null)
        {
            existing = gameObject.AddComponent<BoxCollider2D>();
        }
        existing.isTrigger = true;
        existing.offset = Vector2.zero;
        existing.size = new Vector2(size, size);
    }

    private void ClearChildren()
    {
        // DestroyImmediate to work in editor too
        for (int i = transform.childCount - 1; i >= 0; i--)
        {
            var c = transform.GetChild(i).gameObject;
            // If we're not doing a full clear, preserve children that contain gameplay-critical
            // components (e.g. EnemySpawner). When clearExistingChildren == true we will remove
            // everything (including spawners) as requested by the user.
            if (!clearExistingChildren)
            {
                if (c.GetComponentInChildren<EnemySpawner>() != null || c.GetComponent<EnemySpawner>() != null)
                {
                    // skip deleting spawners when in conservative mode
                    continue;
                }

                // conservative behavior: only delete objects that were generated by this builder
                if (c.GetComponent<RoomBuilderMarker>() == null)
                {
                    // skip designer-placed or unmarked objects
                    continue;
                }
            }

            #if UNITY_EDITOR
            Object.DestroyImmediate(c);
            #else
            Object.Destroy(c);
            #endif
        }
    }

    private void CreateWall(Vector2 localPos, Vector2 size, float zRot, string name)
    {
        GameObject wall;
        if (wallPrefab != null) wall = Instantiate(wallPrefab, transform);
        else
        {
            wall = new GameObject(name);
            wall.transform.SetParent(transform, false);
            var sr = wall.AddComponent<SpriteRenderer>();
            sr.color = Color.black;
        }
        wall.name = name;
        wall.transform.localPosition = new Vector3(localPos.x, localPos.y, 0f);
        wall.transform.localRotation = Quaternion.Euler(0f, 0f, zRot);
        ScaleToSize(wall, size);
        wall.AddComponent<RoomBuilderMarker>();
    }

    private void CreateDoor(Vector3 localPos, float zRot, string name)
    {
        var door = Instantiate(doorPrefab, transform);
        door.name = name;
        door.transform.localPosition = localPos;
        door.transform.localRotation = Quaternion.Euler(0f, 0f, zRot);
        // Ensure door renders above walls: prefer to raise SpriteRenderer.sortingOrder and put as last sibling
        var sr = door.GetComponentInChildren<SpriteRenderer>();
        if (sr != null)
        {
            sr.sortingOrder += 10; // push door forward relative to typical wall sprites
        }
        // Ensure transform is last so it renders after walls in case sorting is equal
        door.transform.SetAsLastSibling();
        door.AddComponent<RoomBuilderMarker>();
    }

    // Scale an instantiated object so that its Renderer bounds match targetSize (in world units).
    // If no renderer is found, apply a direct localScale based on target size.
    private void ScaleToSize(GameObject go, Vector2 targetSize)
    {
        if (go == null) return;
        Renderer r = go.GetComponentInChildren<Renderer>();
        if (r != null)
        {
            var b = r.bounds.size;
            // bounds are world-space; to get local scale factor, consider current lossyScale
            Vector3 lossy = r.transform.lossyScale;
            // approximate original size in local space
            float origX = b.x / lossy.x;
            float origY = b.y / lossy.y;
            Vector3 newScale = go.transform.localScale;
            if (origX != 0f) newScale.x = targetSize.x / origX;
            if (origY != 0f) newScale.y = targetSize.y / origY;
            go.transform.localScale = newScale;
        }
        else
        {
            // no renderer: set scale directly (assume 1 unit base)
            go.transform.localScale = new Vector3(targetSize.x, targetSize.y, 1f);
        }
    }
}

// Marker component placed on GameObjects created by RoomBuilder.
// Used so ClearChildren() can safely remove only builder-generated objects
// and leave designer-placed children intact.
public class RoomBuilderMarker : MonoBehaviour { }
