using System.Collections;
using UnityEngine;

// Controls a single room: when the player enters, close doors and start spawning enemies;
// when all enemies inside the room are dead, open doors again.
public class RoomManager : MonoBehaviour
{
    [Header("Room configuration")]
    // Room trigger is now generated by RoomBuilder and managed at runtime. Hidden to prevent manual edits.
    [HideInInspector]
    public Collider2D roomTrigger;

    // Doors to activate when room is closed. Each side can be assigned or left null.
    public enum DoorDirection { North, East, South, West }

    // Door instances are created by RoomBuilder and discovered at runtime; do not assign manually.
    // Door positions and offsets are managed by RoomBuilder. Door tracking and state
    // are handled by a separate RoomDoors component for readability.
    private RoomDoors roomDoors;

    // Return a world-space point representing the logical exit for the given door direction.
    // If the door GameObject contains a child named "ExitPoint" that Transform will be used
    // (allowing prefab authors to customize the exact anchor). Otherwise the door GameObject
    // position is returned.
    public Vector3 GetDoorEndpoint(DoorDirection dir)
    {
        var door = GetDoor(dir);
        if (door == null) return Vector3.zero;
        var exit = door.transform.Find("ExitPoint");
        if (exit != null) return exit.position;
        return door.transform.position;
    }

    // Helper accessors for external systems (e.g. procedural generator) to query existing doors.
    public GameObject GetDoor(DoorDirection dir)
    {
        if (roomDoors == null) roomDoors = GetComponent<RoomDoors>();
        if (roomDoors == null) return null;
        return roomDoors.GetDoor(dir);
    }

    public bool HasDoor(DoorDirection dir) => GetDoor(dir) != null;

    public GameObject[] GetAllDoors()
    {
        if (roomDoors == null) roomDoors = GetComponent<RoomDoors>();
        if (roomDoors == null) return new GameObject[0];
        return roomDoors.GetAllDoors();
    }

    public enum DoorMode { Normal, PermanentlyLocked }

    // Backwards-compatible accessors that forward to RoomDoors
    public DoorMode GetDoorMode(DoorDirection dir)
    {
        if (roomDoors == null) roomDoors = GetComponent<RoomDoors>();
        return roomDoors != null ? roomDoors.GetDoorMode(dir) : DoorMode.Normal;
    }

    public void SetDoorMode(DoorDirection dir, DoorMode mode)
    {
        if (roomDoors == null) roomDoors = GetComponent<RoomDoors>();
        roomDoors?.SetDoorMode(dir, mode);
    }

    // Enemy spawners inside this room. These will be started when the player enters.
    public EnemySpawner[] enemySpawners;

    [Header("Builder (required)")]
    // RoomBuilder is required. RoomManager will call RoomBuilder.Build(size) to auto-generate
    // floor/walls/doors and the room trigger; designers should not manually place these when
    // using the builder workflow.
    // Room size and prefab configuration are taken from the RoomBuilder on the child object.

    [Header("Runtime")]
    // Set to true while the room is active (player in room and enemies spawning/ alive)
    public bool isRoomActive = false;

    // Delegate invoked when the room has been cleared
    public delegate void OnRoomClearedDelegate();
    public OnRoomClearedDelegate onRoomCleared;

    // Guard to ensure we only trigger entry once per activation
    private bool hasPlayerEntered = false;

    private void Reset()
    {
        // Intentionally left empty: roomTrigger and doors are generated by RoomBuilder.
    }

    private void Awake()
    {
        // Basic validation
        // RoomBuilder is required: ensure the component exists on this GameObject (or a child)
        var builder = GetComponentInChildren<RoomBuilder>(true);
        if (builder == null)
        {
            Debug.LogError($"RoomManager '{name}': RoomBuilder is required. Add a RoomBuilder to this GameObject or its children.");
        }

        // Ensure a RoomDoors component is present to manage door GameObjects
        roomDoors = GetComponent<RoomDoors>();
        if (roomDoors == null)
        {
            roomDoors = gameObject.AddComponent<RoomDoors>();
        }
    }

    private void Start()
    {
        // Build geometry (if configured) then ensure/position doors and open them
        BuildGeometryIfNeeded();
        // Delegate door discovery/opening to RoomDoors component
        roomDoors.EnsureDoorsExist();
        roomDoors.OpenDoors();
        isRoomActive = false;
        hasPlayerEntered = false;
    }

    // Build room geometry using RoomBuilder when configured. Kept separate so Start() stays concise.
    private void BuildGeometryIfNeeded()
    {
        // Find an existing RoomBuilder (do NOT create one automatically).
        RoomBuilder builder = GetComponentInChildren<RoomBuilder>(true);
        if (builder == null)
        {
            Debug.LogError($"RoomManager '{name}': no RoomBuilder found. Please add a RoomBuilder to this GameObject or a child.");
            return;
        }

    // Use the builder's own settings (prefabs & default size)
    float size = builder.defaultSize;
        // If a trigger already exists (previous build), prefer its size
        var existingTrigger = GetComponent<BoxCollider2D>();
        if (existingTrigger != null)
        {
            var s = existingTrigger.size;
            size = Mathf.Max(s.x, s.y);
        }

        builder.Build(size);

    // After builder runs, adopt the trigger it created (builder may be on a child)
    roomTrigger = GetComponentInChildren<BoxCollider2D>(true);
    // Let the RoomDoors rediscover any doors the builder created
    roomDoors.EnsureDoorsExist();
    }

    // Ensure door GameObjects exist (create placeholders if missing) and try to place them at room edges
    // Made public so external systems (e.g. ProceduralDungeonGenerator) can force creation/placement
    public void EnsureDoorsExist()
    {

        // If designer or builder already placed door GameObjects as children with standard names,
        // capture those so we don't instantiate duplicates.
        // (deprecated) Keep EnsureDoorsExist on RoomManager for compatibility by delegating
        // to RoomDoors. This method remains public so external callers can force door
        // discovery immediately after instantiation.
        roomDoors.EnsureDoorsExist();

        // Doors are expected to be generated by RoomBuilder as children named Door_North/East/South/West.
        // We only discover them here; RoomManager will not create placeholder doors.

    // Door positions/rotations are created and managed by RoomBuilder. RoomManager does not reposition doors.
    }

    // Public helper to make sure doors are created and the open/closed visual state is applied.
    // This is useful when rooms are instantiated by editor-time generators which call RoomManager
    // methods immediately after Instantiate (Start may not have executed yet in that context).
    public void InitializeDoors()
    {
        EnsureDoorsExist();
        // Apply open/closed logic using RoomDoors
        roomDoors.OpenDoors();
        // Ensure spawners have a reference to the GameManager when rooms are created by generators
        AssignGameManagerToSpawners();
    }

    // Ensure any EnemySpawner on this room has a reference to the global GameManager instance.
    // This is defensive: generators or designers might forget to wire the reference in the Inspector.
    private void AssignGameManagerToSpawners()
    {
        if (enemySpawners == null || GameManager.instance == null) return;
        foreach (var s in enemySpawners)
        {
            if (s == null) continue;
            if (s.gameManager == null)
            {
                s.gameManager = GameManager.instance;
            }
        }
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (roomTrigger != null && other == null) return;

        // Only respond to player entering. Avoid starting the room for other colliders.
        var player = other.GetComponentInParent<PlayerControllerTest>();
        if (player != null && !hasPlayerEntered)
        {
            // Prefer to verify the player's collider is fully inside the room trigger
            bool fullyInside = false;
            var playerCol = player.GetComponentInChildren<Collider2D>();
            if (playerCol != null && roomTrigger != null)
            {
                var pBounds = playerCol.bounds;
                fullyInside = roomTrigger.bounds.Contains(pBounds.min) && roomTrigger.bounds.Contains(pBounds.max);
            }
            else if (roomTrigger != null)
            {
                // fallback: use player position
                fullyInside = roomTrigger.bounds.Contains(player.transform.position);
            }
            Debug.Log($"RoomManager '{name}': Player entered room trigger. Fully inside: {fullyInside}");

            if (fullyInside)
            {
                hasPlayerEntered = true;
                StartRoom();
            }
            else
            {
                // Player is only partially inside; wait for OnTriggerStay2D to detect full entry
                // Log bounds to help debug why containment failed
                if (roomTrigger == null)
                {
                    Debug.LogWarning($"RoomManager '{name}': roomTrigger is null when checking player containment.");
                }
                else
                {
                    var playerColDebug = player.GetComponentInChildren<Collider2D>();
                    if (playerColDebug != null)
                    {
                        var pB = playerColDebug.bounds;
                        var rB = roomTrigger.bounds;
                        Debug.Log($"RoomManager '{name}': containment failed. Player bounds min={pB.min} max={pB.max} | room bounds min={rB.min} max={rB.max}");
                    }
                    else
                    {
                        var pPos = player.transform.position;
                        var rB = roomTrigger.bounds;
                        Debug.Log($"RoomManager '{name}': containment failed. Player position={pPos} | room bounds min={rB.min} max={rB.max}");
                    }
                }
            }
        }
    }

    private void OnTriggerStay2D(Collider2D other)
    {
        if (roomTrigger != null && other == null) return;
        var player = other.GetComponentInParent<PlayerControllerTest>();
        if (player != null && !hasPlayerEntered)
        {
            bool fullyInside = false;
            var playerCol = player.GetComponentInChildren<Collider2D>();
            if (playerCol != null && roomTrigger != null)
            {
                var pBounds = playerCol.bounds;
                fullyInside = roomTrigger.bounds.Contains(pBounds.min) && roomTrigger.bounds.Contains(pBounds.max);
                Debug.Log($"RoomManager '{name}': OnTriggerStay2D checking player full entry. Fully inside: {fullyInside}");
            }
            else if (roomTrigger != null)
            {
                fullyInside = roomTrigger.bounds.Contains(player.transform.position);
            }

            if (fullyInside)
            {
                hasPlayerEntered = true;
                StartRoom();
            }
                else
                {
                    // Player is only partially inside; log bounds to diagnose
                    if (roomTrigger == null)
                    {
                        Debug.LogWarning($"RoomManager '{name}': roomTrigger is null when checking player containment (Stay).");
                    }
                    else
                    {
                        var playerColDebug = player.GetComponentInChildren<Collider2D>();
                        if (playerColDebug != null)
                        {
                            var pB = playerColDebug.bounds;
                            var rB = roomTrigger.bounds;
                            Debug.Log($"RoomManager '{name}': (Stay) containment failed. Player bounds min={pB.min} max={pB.max} | room bounds min={rB.min} max={rB.max}");
                        }
                        else
                        {
                            var pPos = player.transform.position;
                            var rB = roomTrigger.bounds;
                            Debug.Log($"RoomManager '{name}': (Stay) containment failed. Player position={pPos} | room bounds min={rB.min} max={rB.max}");
                        }
                    }
                }
        }
    }

    // Made public so DungeonManager can activate rooms
    public void StartRoom()
    {
        isRoomActive = true;
        // Close doors via RoomDoors
        roomDoors.CloseDoors();
        StartSpawners();

        // Determine how many spawners are finite (will eventually finish).
        int spawnersToFinish = 0;
        if (enemySpawners != null && enemySpawners.Length > 0)
        {
            foreach (var s in enemySpawners)
            {
                if (s == null) continue;
                // subscribe to finished event so we know when finite spawners complete
                s.OnSpawnerFinished += OnSpawnerFinished;
                if (s.HasFiniteWaves()) spawnersToFinish++;
            }
        }

        if (spawnersToFinish > 0)
        {
            // We'll wait for the OnSpawnerFinished callbacks to open doors.
            pendingSpawnersToFinish = spawnersToFinish;
        }
        else
        {
            // No finite spawners; poll spawners until they are all idle (no active waves)
            StartCoroutine(PollSpawnersUntilIdle());
        }
    }

    private int pendingSpawnersToFinish = 0;

    private void OnSpawnerFinished()
    {
        pendingSpawnersToFinish--;
        if (pendingSpawnersToFinish <= 0)
        {
            // Room cleared
            isRoomActive = false;
            OpenDoors();
            onRoomCleared?.Invoke();
            // Notify game manager that this room is cleared
            GameManager.instance?.RoomCleared(this);
        }
    }

    private IEnumerator PollSpawnersUntilIdle()
    {
        // Wait a frame so spawners can initialize
        yield return null;

        while (true)
        {
            bool anyActive = false;
            if (enemySpawners != null)
            {
                foreach (var s in enemySpawners)
                {
                    if (s == null) continue;
                    if (s.IsWaveActive)
                    {
                        anyActive = true;
                        break;
                    }
                }
            }

            if (!anyActive)
            {
                Debug.Log($"RoomManager '{name}': All spawners idle, room cleared.");
                // No active waves across spawners — consider room cleared
                isRoomActive = false;
                OpenDoors();
                onRoomCleared?.Invoke();
                // Notify game manager that this room is cleared
                GameManager.instance?.RoomCleared(this);
                yield break;
            }

            yield return new WaitForSeconds(0.25f);
        }
    }

    private void CloseDoors()
    {
        // kept for compatibility - delegate
        roomDoors.CloseDoors();
    }

    private void OpenDoors()
    {
        // kept for compatibility - delegate
        roomDoors.OpenDoors();
    }

    private void StartSpawners()
    {
        if (enemySpawners == null) return;
        foreach (var s in enemySpawners)
        {
            if (s == null) continue;
            // Try to call StartWave if available (matches GameManager usage)
            s.StartWave();
        }
    }

    // Optional helper to force-clear the room (useful for debugging / level design)
    public void ForceClearRoom()
    {
        StopAllCoroutines();
        isRoomActive = false;
        OpenDoors();
        onRoomCleared?.Invoke();
    }
}
