using System.Collections;
using UnityEngine;

// Controls a single room: when the player enters, close doors and start spawning enemies;
// when all enemies inside the room are dead, open doors again.
public class RoomManager : MonoBehaviour
{
    [Header("Room configuration")]
    // Room trigger is now generated by RoomBuilder and managed at runtime. Hidden to prevent manual edits.
    [HideInInspector]
    public Collider2D roomTrigger;

    // Doors to activate when room is closed. Each side can be assigned or left null.
    public enum DoorDirection { North, East, South, West }

    // Door GameObjects and modes are stored on RoomManager. RoomDoors is a static helper.
    public GameObject doorNorth;
    public GameObject doorEast;
    public GameObject doorSouth;
    public GameObject doorWest;

    public DoorMode doorNorthMode = DoorMode.Normal;
    public DoorMode doorEastMode = DoorMode.Normal;
    public DoorMode doorSouthMode = DoorMode.Normal;
    public DoorMode doorWestMode = DoorMode.Normal;

    [Header("Builder (prefabs & options)")]
    // Prefabs and layout options (moved from RoomBuilder into RoomManager)
    public GameObject floorPrefab;
    public GameObject wallPrefab;
    public GameObject doorPrefab;
    public float wallThickness = 0.5f;
    public float doorOutsideOffset = 0.1f;
    public float defaultSize = 8f;
    public bool clearExistingChildren = false;

    // Return a world-space point representing the logical exit for the given door direction.
    // If the door GameObject contains a child named "ExitPoint" that Transform will be used
    // (allowing prefab authors to customize the exact anchor). Otherwise the door GameObject
    // position is returned.
    public Vector3 GetDoorEndpoint(DoorDirection dir)
    {
        var door = GetDoor(dir);
        if (door == null) return Vector3.zero;
        var exit = door.transform.Find("ExitPoint");
        if (exit != null) return exit.position;
        return door.transform.position;
    }

    // Helper accessors for external systems (e.g. procedural generator) to query existing doors.
    public GameObject GetDoor(DoorDirection dir) => RoomDoors.GetDoor(this, dir);

    public bool HasDoor(DoorDirection dir) => GetDoor(dir) != null;

    public GameObject[] GetAllDoors() => RoomDoors.GetAllDoors(this);

    public enum DoorMode { Normal, PermanentlyLocked }

    // Backwards-compatible accessors that forward to RoomDoors
    public DoorMode GetDoorMode(DoorDirection dir) => RoomDoors.GetDoorMode(this, dir);

    public void SetDoorMode(DoorDirection dir, DoorMode mode) => RoomDoors.SetDoorMode(this, dir, mode);

    // Enemy spawner inside this room. This project uses a single spawner per room.
    // Assign the spawner in the Inspector to `enemySpawner`.
    public EnemySpawner enemySpawner;

    [Header("Builder (required)")]
    // RoomBuilder is required. RoomManager will call RoomBuilder.Build(size) to auto-generate
    // floor/walls/doors and the room trigger; designers should not manually place these when
    // using the builder workflow.
    // Room size and prefab configuration are taken from the RoomBuilder on the child object.

    [Header("Runtime")]
    // Set to true while the room is active (player in room and enemies spawning/ alive)
    public bool isRoomActive = false;

    // Delegate invoked when the room has been cleared
    public delegate void OnRoomClearedDelegate();
    public OnRoomClearedDelegate onRoomCleared;

    // Guard to ensure we only trigger entry once per activation
    private bool hasPlayerEntered = false;

    private void Reset()
    {
        // Intentionally left empty: roomTrigger and doors are generated by RoomBuilder.
    }

    private void Awake()
    {
        // No longer requiring a RoomBuilder component: RoomManager holds builder settings.
    }

    private void Start()
    {
        // Build geometry (if configured) then ensure/position doors and open them
        BuildGeometryIfNeeded();
        // Delegate door discovery/opening to static RoomDoors helper
        //RoomDoors.EnsureDoorsExist(this);
        RoomDoors.OpenDoors(this);
        isRoomActive = false;
        hasPlayerEntered = false;
    }

    // Build room geometry using RoomBuilder when configured. Kept separate so Start() stays concise.
    private void BuildGeometryIfNeeded()
    {
        // Use RoomManager settings and the static RoomBuilder helper to create geometry.
        float size = defaultSize;
        var existingTrigger = GetComponent<BoxCollider2D>();
        if (existingTrigger != null)
        {
            var s = existingTrigger.size;
            size = Mathf.Max(s.x, s.y);
        }

        RoomBuilder.Build(transform, size, floorPrefab, wallPrefab, doorPrefab, wallThickness, doorOutsideOffset, clearExistingChildren);

        // After builder runs, adopt the trigger it created (builder may be on a child)
        roomTrigger = GetComponentInChildren<BoxCollider2D>(true);
        // Let the RoomDoors rediscover any doors the builder created
        RoomDoors.EnsureDoorsExist(this);
    }

    // Public helper to make sure doors are created and the open/closed visual state is applied.
    // This is useful when rooms are instantiated by editor-time generators which call RoomManager
    // methods immediately after Instantiate (Start may not have executed yet in that context).
    public void InitializeDoors()
    {
        RoomDoors.EnsureDoorsExist(this);
        // Apply open/closed logic using RoomDoors
        RoomDoors.OpenDoors(this);
        // Ensure spawners have a reference to the GameManager when rooms are created by generators
        AssignGameManagerToSpawners();
    }

    // Ensure any EnemySpawner on this room has a reference to the global GameManager instance.
    // This is defensive: generators or designers might forget to wire the reference in the Inspector.
    private void AssignGameManagerToSpawners()
    {
        if (GameManager.instance == null) return;
        if (enemySpawner != null && enemySpawner.gameManager == null)
        {
            enemySpawner.gameManager = GameManager.instance;
        }
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (roomTrigger != null && other == null) return;

        // Only respond to player entering. Avoid starting the room for other colliders.
        var player = other.GetComponentInParent<PlayerController>();
        if (player != null && !hasPlayerEntered)
        {
            // Prefer to verify the player's collider is fully inside the room trigger
            bool fullyInside = false;
            var playerCol = player.GetComponentInChildren<Collider2D>();
            if (playerCol != null && roomTrigger != null)
            {
                var pBounds = playerCol.bounds;
                fullyInside = roomTrigger.bounds.Contains(pBounds.min) && roomTrigger.bounds.Contains(pBounds.max);
            }
            else if (roomTrigger != null)
            {
                // fallback: use player position
                fullyInside = roomTrigger.bounds.Contains(player.transform.position);
            }

            if (fullyInside)
            {
                hasPlayerEntered = true;
                StartRoom();
            }
        }
    }

    private void OnTriggerStay2D(Collider2D other)
    {
        if (roomTrigger != null && other == null) return;
        var player = other.GetComponentInParent<PlayerController>();
        if (player != null && !hasPlayerEntered)
        {
            bool fullyInside = false;
            var playerCol = player.GetComponentInChildren<Collider2D>();
            if (playerCol != null && roomTrigger != null)
            {
                var pBounds = playerCol.bounds;
                fullyInside = roomTrigger.bounds.Contains(pBounds.min) && roomTrigger.bounds.Contains(pBounds.max);
            }
            else if (roomTrigger != null)
            {
                fullyInside = roomTrigger.bounds.Contains(player.transform.position);
            }

            if (fullyInside)
            {
                hasPlayerEntered = true;
                StartRoom();
            }
        }
    }

    // Made public so DungeonManager can activate rooms
    public void StartRoom()
    {
        // If there's no spawner in this room, consider it immediately cleared.
        if (enemySpawner == null)
        {
            Debug.Log($"RoomManager '{name}': no spawner assigned — marking room cleared on entry.");
            isRoomActive = false;
            // Ensure doors remain open and notify listeners
            OpenDoors();
            onRoomCleared?.Invoke();
            GameManager.instance?.RoomCleared(this);
            return;
        }

        isRoomActive = true;
        // Close doors via RoomDoors
        CloseDoors();
        enemySpawner.StartWave();

        // Single-spawner logic: if the spawner is finite, subscribe and wait for its
        // OnSpawnerFinished event to open doors. Otherwise poll until idle.
        if (enemySpawner != null)
        {
            // Only subscribe if the spawner is finite (will signal completion).
            if (enemySpawner.HasFiniteWaves())
            {
                // Ensure we don't double-subscribe
                enemySpawner.OnSpawnerFinished -= OnSpawnerFinished;
                enemySpawner.OnSpawnerFinished += OnSpawnerFinished;
                // Wait for the spawner to signal completion via event
                return;
            }
        }

        // No finite spawner subscribed — poll until spawner(s) become idle
        StartCoroutine(PollSpawnersUntilIdle());
    }

    private void OnSpawnerFinished()
    {
        // Single-spawner finished: unsubscribe and clear the room
        if (enemySpawner != null) enemySpawner.OnSpawnerFinished -= OnSpawnerFinished;

        isRoomActive = false;
        OpenDoors();
        onRoomCleared?.Invoke();
        // Notify game manager that this room is cleared
        GameManager.instance?.RoomCleared(this);
    }

    private IEnumerator PollSpawnersUntilIdle()
    {
        // Wait a frame so spawners can initialize
        yield return null;

        while (true)
        {
            bool anyActive = false;
            // Single spawner check
            if (enemySpawner != null && enemySpawner.IsWaveActive)
            {
                anyActive = true;
            }

            if (!anyActive)
            {
                // No active waves across spawners — consider room cleared
                isRoomActive = false;
                OpenDoors();
                onRoomCleared?.Invoke();
                // Notify game manager that this room is cleared
                GameManager.instance?.RoomCleared(this);
                yield break;
            }

            yield return new WaitForSeconds(0.25f);
        }
    }

    private void CloseDoors()
    {
        // delegated to static helper
        RoomDoors.CloseDoors(this);
    }

    private void OpenDoors()
    {
        // delegated to static helper
        RoomDoors.OpenDoors(this);
    }

    // Optional helper to force-clear the room (useful for debugging / level design)
    public void ForceClearRoom()
    {
        StopAllCoroutines();
        isRoomActive = false;
        OpenDoors();
        // Ensure we unsubscribe from spawner events when force-clearing
        if (enemySpawner != null) enemySpawner.OnSpawnerFinished -= OnSpawnerFinished;
        onRoomCleared?.Invoke();
    }
}
